### ISSUE TITLE
As a Front-End engineer, I want to be able to create the Tinder card-swiping mechanism, so that users can select and pick the profiles I want to connect with

### ISSUE THREAD

**Issue by omarTl** [scalableinternetservices/linksin#4]
As a Front-End engineer, I want to be able to create the Tinder card-swiping mechanism, so that users can select and pick the profiles I want to connect with

**Comment by Phipson** [comment]
Refer to the following links:

https://stackoverflow.com/questions/35918118/ruby-on-rails-best-way-to-implement-tinder-behavior
https://hackernoon.com/how-to-build-and-launch-a-dating-app-in-a-week-759e6d32b764
https://github.com/lsecrease/rails-tinder
https://github.com/brandonsturgeon/rubr

**Comment by Phipson** [comment]
Added Card-swiping mechanism- now need to link it with our user profile models
