### ISSUE TITLE
Default database data should be auto generated when the app first runs

### ISSUE THREAD

**Issue by junhongwang418** [scalableinternetservices/linksin#67]
So that we don't have to manually create users every time we deploy our app for demo

**Comment by omarTl** [comment]
https://rubygems.org/gems/faker
https://github.com/faker-ruby/faker
We can take a look at this

**Comment by omarTl** [comment]
Actually db:seed seems like an easier option

**Comment by junhongwang418** [comment]
Thanks @omarTl
